# Generated by Django 4.2 on 2023-04-11 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('telegram_id', models.IntegerField(default=-1, verbose_name='ID телеграм')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('telegram_id', models.IntegerField(default=-1, unique=True, verbose_name='ID телеграм')),
                ('name', models.CharField(max_length=60, verbose_name='Имя пользователя')),
                ('subscription_end', models.DateField(default=datetime.date.today, verbose_name='Дата окончания подписки')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
